allowBuilds:
  '@antv/l7-react': true
  '@google/genai': true
  '@scarf/scarf': true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  nice-napi: true
  protobufjs: true
  puppeteer-core: true
  unrs-resolver: true
