#!/usr/bin/env python3
"""
Stage 4: 去除AI标记 — 批量剥离 Suno/AI 生成的音频文件中的 AI 元数据标记

功能：
- 批量扫描目录下的音频文件（MP3/WAV/FLAC/OGG/M4A）
- 用 ffmpeg 剥离所有非音频元数据
- 可选保留封面图
- 可选仅删除特定 AI 标签字段（保留其他元数据）
- 智能模式：检测并仅删除 AI 相关字段
- 输出详细日志，记录每个文件的操作结果

用法：
    python stage4_strip_ai_tags.py -i /path/to/input/dir -o /path/to/output/dir
    python stage4_strip_ai_tags.py -i /path/to/input/dir --in-place   # 原地替换
    python stage4_strip_ai_tags.py -i /path/to/input/dir --smart     # 智能模式
    python stage4_strip_ai_tags.py -i /path/to/input/dir --dry-run   # 预览模式

兼容：独立运行 ｜ 集成到流水线 ｜ 作为 Python 模块 import
"""

import argparse
import json
import logging
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List, Optional, Tuple

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("strip_ai_tags")

# ============================================================================
# 配置
# ============================================================================

# Suno / AI 相关敏感关键词（用于智能模式检测）
AI_KEYWORDS = [
    "suno", "udio", "ai", "artificial intelligence", "generated by",
    "ai generated", "generated with", "powered by", "created by ai",
    "machine learning", "deep learning", "neural", "suno inc",
    "udio.com", "suno.ai", "suno ai", "audio-cleaner", "cleaner audio",
]

# 支持的文件格式
SUPPORTED_EXTENSIONS = {".mp3", ".wav", ".flac", ".ogg", ".m4a", ".aiff", ".wma"}


# ============================================================================
# 核心功能
# ============================================================================


def check_ffmpeg() -> bool:
    """检查 ffmpeg 是否可用"""
    try:
        subprocess.run(
            ["ffmpeg", "-version"],
            capture_output=True,
            check=True,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def get_audio_metadata(file_path: Path) -> dict:
    """用 ffprobe 读取音频文件的元数据"""
    try:
        result = subprocess.run(
            [
                "ffprobe",
                "-v", "quiet",
                "-print_format", "json",
                "-show_format",
                "-show_streams",
                str(file_path),
            ],
            capture_output=True,
            encoding='utf-8', errors='replace',
            timeout=30,
        )
        data = json.loads(result.stdout)

        metadata = {}
        if "format" in data and "tags" in data["format"]:
            metadata.update(data["format"]["tags"])
        for stream in data.get("streams", []):
            if "tags" in stream:
                metadata.update(stream["tags"])

        return metadata
    except (subprocess.CalledProcessError, json.JSONDecodeError, TimeoutError) as e:
        logger.warning(f"无法读取元数据: {file_path.name} — {e}")
        return {}


def detect_ai_tags(file_or_metadata) -> Tuple[List[str], List[str]]:
    """
    智能检测元数据中的 AI 标记
    接受文件路径 (str/Path) 或已读取的元数据字典
    返回: (匹配的字段名列表, 匹配的字段值列表)
    """
    if isinstance(file_or_metadata, (str, Path)):
        metadata = get_audio_metadata(Path(file_or_metadata))
    elif isinstance(file_or_metadata, dict):
        metadata = file_or_metadata
    else:
        return [], []

    matched_keys = []
    matched_values = []
    for key, value in metadata.items():
        key_lower = key.lower()
        value_lower = str(value).lower()
        for kw in AI_KEYWORDS:
            if kw in key_lower or kw in value_lower:
                matched_keys.append(key)
                matched_values.append(f"{key} = {value}")
                break

    return matched_keys, matched_values


def strip_metadata_via_ffmpeg(
    input_path: Path,
    output_path: Path,
    keep_cover: bool = True,
) -> bool:
    """
    使用 ffmpeg 剥离元数据（暴力模式）
    """
    cmd = ["ffmpeg", "-y", "-i", str(input_path)]
    cmd.extend(["-map_metadata", "-1"])

    if keep_cover:
        cmd.extend(["-map", "0"])
    else:
        cmd.extend(["-map", "0:a"])

    cmd.extend([
        "-metadata", "encoded_by=",
        "-metadata", "encoder=",
        "-metadata", "comment=",
        "-metadata", "description=",
        "-metadata", "publisher=",
    ])

    cmd.extend(["-codec", "copy", str(output_path)])

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            encoding='utf-8', errors='replace',
            timeout=120,
        )

        if result.returncode == 0 and output_path.exists() and output_path.stat().st_size > 0:
            logger.info(f"✅ ffmpeg 剥离成功: {input_path.name}")
            return True
        else:
            logger.error(f"❌ ffmpeg 剥离失败: {input_path.name} — {result.stderr[:200]}")
            return False

    except subprocess.TimeoutExpired:
        logger.error(f"⏰ 超时: {input_path.name}")
        return False
    except Exception as e:
        logger.error(f"💥 异常: {input_path.name} — {e}")
        return False


def strip_metadata_smart(input_path: Path, output_path: Path) -> bool:
    """
    智能模式：使用 mutagen 精确控制，只删除 AI 相关字段
    """
    try:
        import mutagen
        from mutagen.id3 import ID3, ID3NoHeaderError
        from mutagen.flac import FLAC
        from mutagen.mp4 import MP4
        from mutagen.oggvorbis import OggVorbis
        from mutagen.wave import WAVE
    except ImportError:
        logger.warning("mutagen 未安装，回退到 ffmpeg 暴力模式")
        return strip_metadata_via_ffmpeg(input_path, output_path, keep_cover=True)

    ext = input_path.suffix.lower()
    shutil.copy2(input_path, output_path)

    try:
        modified = False
        ai_fields_removed = []

        if ext == ".mp3":
            try:
                audio = ID3(output_path)
            except ID3NoHeaderError:
                audio = None
            if audio:
                frames_to_remove = []
                for frame_id in audio.keys():
                    frame_str = str(audio[frame_id])
                    for kw in AI_KEYWORDS:
                        if kw in frame_id.lower() or kw in frame_str.lower():
                            frames_to_remove.append(frame_id)
                            ai_fields_removed.append(f"{frame_id}: {frame_str[:80]}")
                            break
                for frame_id in frames_to_remove:
                    del audio[frame_id]
                    modified = True
                if modified:
                    audio.save(output_path)

        elif ext == ".flac":
            try:
                audio = FLAC(output_path)
                fields_to_remove = []
                for key in list(audio.keys()):
                    for kw in AI_KEYWORDS:
                        if kw in key.lower():
                            fields_to_remove.append(key)
                            ai_fields_removed.append(f"{key}: {audio[key]}")
                            break
                    else:
                        for val in audio.get(key, []):
                            if any(kw in str(val).lower() for kw in AI_KEYWORDS):
                                fields_to_remove.append(key)
                                ai_fields_removed.append(f"{key}: {audio[key]}")
                                break
                for field in fields_to_remove:
                    del audio[field]
                    modified = True
                if modified:
                    audio.save()
            except Exception:
                pass

        elif ext in (".m4a", ".mp4"):
            try:
                audio = MP4(output_path)
                fields_to_remove = []
                for key in list(audio.keys()):
                    for kw in AI_KEYWORDS:
                        if kw in key.lower() or kw in str(audio[key]).lower():
                            fields_to_remove.append(key)
                            ai_fields_removed.append(f"{key}: {audio[key]}")
                            break
                for field in fields_to_remove:
                    del audio[field]
                    modified = True
                if modified:
                    audio.save()
            except Exception:
                pass

        elif ext == ".ogg":
            try:
                audio = OggVorbis(output_path)
                fields_to_remove = []
                for key in list(audio.keys()):
                    for kw in AI_KEYWORDS:
                        if kw in key.lower():
                            fields_to_remove.append(key)
                            break
                    else:
                        if any(kw in str(val).lower() for val in audio.get(key, []) for kw in AI_KEYWORDS):
                            fields_to_remove.append(key)
                for field in fields_to_remove:
                    del audio[field]
                    modified = True
                if modified:
                    audio.save()
            except Exception:
                pass

        if ext == ".wav":
            return strip_metadata_via_ffmpeg(input_path, output_path)

        if modified:
            logger.info(f"🔍 [智能] 删除 {len(ai_fields_removed)} 个 AI 标记: {input_path.name}")
            for field in ai_fields_removed:
                logger.debug(f"  删除: {field}")
        else:
            logger.info(f"✅ [智能] 无 AI 标记: {input_path.name}")

        return True

    except Exception as e:
        logger.error(f"💥 [智能] 处理失败: {input_path.name} — {e}")
        output_path.unlink(missing_ok=True)
        return strip_metadata_via_ffmpeg(input_path, output_path, keep_cover=True)


def process_file(
    input_path: Path,
    output_dir: Path,
    mode: str = "ffmpeg",
    in_place: bool = False,
    keep_cover: bool = True,
    dry_run: bool = False,
) -> bool:
    """处理单个音频文件"""
    if input_path.suffix.lower() not in SUPPORTED_EXTENSIONS:
        logger.debug(f"跳过不支持格式: {input_path.name}")
        return False

    if dry_run:
        metadata = get_audio_metadata(input_path)
        if metadata:
            ai_keys, ai_vals = detect_ai_tags(metadata)
            if ai_keys:
                logger.info(f"🔍 [预览] {input_path.name} — 发现 {len(ai_keys)} 个 AI 标记:")
                for v in ai_vals:
                    logger.info(f"        {v}")
            else:
                logger.info(f"✅ [预览] {input_path.name} — 未发现 AI 标记")
        else:
            logger.info(f"ℹ️  [预览] {input_path.name} — 无元数据")
        return True

    if in_place:
        tmp_fd, tmp_path_str = tempfile.mkstemp(suffix=input_path.suffix)
        os.close(tmp_fd)
        output_path = Path(tmp_path_str)
        final_path = input_path
    else:
        output_path = output_dir / input_path.name
        final_path = output_path

    if mode == "smart":
        success = strip_metadata_smart(input_path, output_path)
    else:
        success = strip_metadata_via_ffmpeg(input_path, output_path, keep_cover)

    if success and in_place:
        shutil.move(str(output_path), str(final_path))
        logger.info(f"🔄 [原地] {input_path.name} 已更新")

    return success


def process_directory(
    input_dir: Path,
    output_dir: Path,
    mode: str = "ffmpeg",
    in_place: bool = False,
    keep_cover: bool = True,
    dry_run: bool = False,
    recursive: bool = False,
) -> Tuple[int, int]:
    """批量处理目录中的所有音频文件"""
    files = []
    glob_pattern = "**/*" if recursive else "*"

    for ext in SUPPORTED_EXTENSIONS:
        for f in input_dir.glob(f"{glob_pattern}{ext}"):
            if f.is_file():
                files.append(f)

    if not files:
        logger.warning(f"在 {input_dir} 中未找到支持的音频文件")
        return 0, 0

    logger.info(f"📂 找到 {len(files)} 个音频文件")

    if not dry_run and not in_place:
        output_dir.mkdir(parents=True, exist_ok=True)

    success_count = 0
    for i, file_path in enumerate(files, 1):
        logger.info(f"[{i}/{len(files)}] 处理: {file_path.name}")
        try:
            if process_file(
                input_path=file_path,
                output_dir=output_dir,
                mode=mode,
                in_place=in_place,
                keep_cover=keep_cover,
                dry_run=dry_run,
            ):
                success_count += 1
        except Exception as e:
            logger.error(f"处理 {file_path.name} 时出错: {e}")

    return success_count, len(files)


# ============================================================================
# 流水线集成类
# ============================================================================

class AITagStripper:
    """流水线集成类"""

    def __init__(self, mode: str = "ffmpeg", keep_cover: bool = True):
        self.mode = mode
        self.keep_cover = keep_cover
        self.stats = {"processed": 0, "success": 0, "ai_found": 0, "failed": 0}

    def process_file(self, input_path: str, output_path: str = None) -> bool:
        inp = Path(input_path)
        out = Path(output_path) if output_path else inp
        self.stats["processed"] += 1
        success = strip_metadata_via_ffmpeg(inp, out, self.keep_cover)
        if success:
            self.stats["success"] += 1
        else:
            self.stats["failed"] += 1
        return success

    def process_directory(self, input_dir: str, output_dir: str = None) -> dict:
        inp_dir = Path(input_dir)
        out_dir = Path(output_dir) if output_dir else inp_dir
        if out_dir != inp_dir:
            out_dir.mkdir(parents=True, exist_ok=True)
        success, total = process_directory(
            input_dir=inp_dir,
            output_dir=out_dir,
            mode=self.mode,
            keep_cover=self.keep_cover,
        )
        return {"total": total, "success": success, "failed": total - success}

    def get_stats(self) -> dict:
        return self.stats

    def reset_stats(self):
        self.stats = {"processed": 0, "success": 0, "ai_found": 0, "failed": 0}


# ============================================================================
# 自检
# ============================================================================

def run_self_test():
    logger.info("🧪 运行自检...")

    if not check_ffmpeg():
        logger.error("❌ ffmpeg 未找到")
        return False
    logger.info("✅ ffmpeg 可用")

    try:
        import mutagen
        logger.info(f"✅ mutagen {mutagen.version_string} 可用")
    except ImportError:
        logger.warning("⚠️ mutagen 未安装，智能模式不可用")

    tmp_dir = Path(tempfile.mkdtemp(prefix="ai_tag_test_"))
    test_file = tmp_dir / "test_suno_song.mp3"

    try:
        subprocess.run([
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
            "-t", "1",
            "-metadata", "title=Test Song",
            "-metadata", "artist=Test Artist",
            "-metadata", "encoded_by=Suno AI v4",
            "-metadata", "comment=Generated by Suno AI",
            "-metadata", "encoder=Suno AI Inc.",
            str(test_file),
        ], capture_output=True, check=True)

        metadata = get_audio_metadata(test_file)
        logger.info(f"📋 原始元数据: {json.dumps(metadata, indent=2)}")

        keys, vals = detect_ai_tags(metadata)
        if keys:
            logger.info(f"🔍 检测到 {len(keys)} 个 AI 标记: {keys}")
        else:
            logger.warning("⚠️ 未检测到 AI 标记")

        out_file = tmp_dir / "test_cleaned.mp3"
        success = strip_metadata_via_ffmpeg(test_file, out_file)

        if success:
            clean_meta = get_audio_metadata(out_file)
            logger.info(f"📋 清理后元数据: {json.dumps(clean_meta, indent=2)}")
            ai_keys_after, _ = detect_ai_tags(clean_meta)
            if not ai_keys_after:
                logger.info("✅ 自检通过！AI 标记已全部清除")
            else:
                logger.warning(f"⚠️ 仍有残留 AI 标记: {ai_keys_after}")
        else:
            logger.error("❌ 自检失败")

    except Exception as e:
        logger.error(f"💥 自检异常: {e}")
        return False
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        logger.info("🧹 测试文件已清理")

    return True


# ============================================================================
# CLI
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="🎵 Stage 4: 去除AI标记 — 批量剥离 Suno/AI 音频元数据",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
使用示例:
  %(prog)s -i ./suno_output -o ./cleaned
  %(prog)s -i ./suno_output --in-place
  %(prog)s -i ./suno_output --smart
  %(prog)s -i ./suno_output --dry-run
  %(prog)s --self-test
        """,
    )

    parser.add_argument("-i", "--input-dir", type=str, required=False,
                        help="输入目录（包含 Suno 输出的音频文件）")
    parser.add_argument("-o", "--output-dir", type=str, default=None,
                        help="输出目录（默认: input_dir/cleaned）")
    parser.add_argument("--in-place", action="store_true",
                        help="原地替换（直接修改原文件）")
    parser.add_argument("--smart", action="store_true",
                        help="智能模式（精确删除 AI 字段）")
    parser.add_argument("--no-cover", action="store_true",
                        help="不保留封面图")
    parser.add_argument("--recursive", action="store_true",
                        help="递归搜索子目录")
    parser.add_argument("--dry-run", action="store_true",
                        help="预览模式（只检测不处理）")
    parser.add_argument("--self-test", action="store_true",
                        help="运行自检")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="详细日志")

    args = parser.parse_args()

    if args.verbose:
        logger.setLevel(logging.DEBUG)

    if args.self_test:
        success = run_self_test()
        sys.exit(0 if success else 1)

    if not check_ffmpeg():
        msg = "❌ 需要 ffmpeg！请安装: https://ffmpeg.org/download.html"
        if sys.platform == "linux":
            msg += "\n   Linux: sudo apt install ffmpeg"
        logger.error(msg)
        sys.exit(1)

    if not args.input_dir:
        parser.print_help()
        logger.error("请指定输入目录 (-i) 或使用 --self-test")
        sys.exit(1)

    input_dir = Path(args.input_dir).expanduser().resolve()
    if not input_dir.exists():
        logger.error(f"❌ 目录不存在: {input_dir}")
        sys.exit(1)

    if args.in_place:
        output_dir = input_dir
    elif args.output_dir:
        output_dir = Path(args.output_dir).expanduser().resolve()
    else:
        output_dir = input_dir / "cleaned"

    mode = "smart" if args.smart else "ffmpeg"

    logger.info("=" * 60)
    logger.info("🎵 Stage 4: 去除AI标记")
    logger.info(f"📂 输入: {input_dir}")
    logger.info(f"📂 输出: {output_dir}")
    logger.info(f"⚙️  模式: {'智能' if mode == 'smart' else '暴力(ffmpeg)'}")
    logger.info(f"🖼️  保留封面: {'否' if args.no_cover else '是'}")
    logger.info(f"👀 预览: {'是' if args.dry_run else '否'}")
    logger.info("=" * 60)

    success, total = process_directory(
        input_dir=input_dir,
        output_dir=output_dir,
        mode=mode,
        in_place=args.in_place,
        keep_cover=not args.no_cover,
        dry_run=args.dry_run,
        recursive=args.recursive,
    )

    logger.info("=" * 60)
    if args.dry_run:
        logger.info(f"🔍 预览完成: {total} 个文件检查")
    else:
        logger.info(f"📊 结果: {success}/{total} 成功 | {total - success} 失败")
        if success == total:
            logger.info("🎉 全部搞定！")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
